# Generated by Django 4.2.7 on 2026-03-28 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Card_Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_chf", models.DecimalField(decimal_places=2, max_digits=8)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("MT", "Mint"),
                            ("NM", "Near Mint"),
                            ("LP", "Lightly Played"),
                            ("MP", "Moderately Played"),
                            ("HP", "Heavily Played"),
                            ("DMG", "Damaged"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "is_graded",
                    models.CharField(
                        choices=[
                            ("RAW", "Raw (Ungraded)"),
                            ("PSA", "PSA Graded"),
                            ("BGS", "BGS Graded"),
                            ("CGC", "CGC Graded"),
                            ("TAG", "TAG Graded"),
                            ("ACE", "ACE Graded"),
                        ],
                        default="RAW",
                        max_length=4,
                    ),
                ),
                (
                    "seller_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Seller-provided high-resolution photo of the actual card.",
                        null=True,
                        upload_to="listing_photos/%Y/%m/",
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Set_Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_code", models.CharField(max_length=20, unique=True)),
                ("set_name", models.CharField(max_length=100)),
                ("total_cards", models.IntegerField(default=0)),
                ("printed_total", models.IntegerField(default=0)),
                ("ptcgo_code", models.CharField(blank=True, max_length=10, null=True)),
                ("series", models.CharField(blank=True, max_length=100, null=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("symbol_url", models.URLField(blank=True, default="", max_length=500)),
                ("logo_url", models.URLField(blank=True, default="", max_length=500)),
                ("legalities", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Set Masters",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipping_name", models.CharField(default="", max_length=100)),
                (
                    "shipping_address_line1",
                    models.CharField(default="", max_length=200),
                ),
                (
                    "shipping_address_line2",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("shipping_city", models.CharField(default="", max_length=100)),
                ("shipping_postal_code", models.CharField(default="", max_length=20)),
                ("shipping_country", models.CharField(default="", max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price_chf", models.DecimalField(decimal_places=2, max_digits=8)),
                ("shipping_name", models.CharField(default="", max_length=100)),
                (
                    "shipping_address_line1",
                    models.CharField(default="", max_length=200),
                ),
                (
                    "shipping_address_line2",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("shipping_city", models.CharField(default="", max_length=100)),
                ("shipping_postal_code", models.CharField(default="", max_length=20)),
                ("shipping_country", models.CharField(default="", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="api.card_listing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Card_Master",
            fields=[
                (
                    "api_id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("card_name", models.CharField(max_length=255)),
                ("card_number", models.CharField(max_length=10)),
                (
                    "secondary_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("card_rarity", models.CharField(max_length=50)),
                ("image_url", models.URLField(max_length=500)),
                ("supertype", models.CharField(blank=True, default="", max_length=50)),
                ("subtypes", models.JSONField(blank=True, default=list)),
                ("hp", models.CharField(blank=True, default="", max_length=10)),
                ("types", models.JSONField(blank=True, default=list)),
                (
                    "evolves_from",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("evolves_to", models.JSONField(blank=True, default=list)),
                ("attacks", models.JSONField(blank=True, default=list)),
                ("abilities", models.JSONField(blank=True, default=list)),
                ("weaknesses", models.JSONField(blank=True, default=list)),
                ("resistances", models.JSONField(blank=True, default=list)),
                ("retreat_cost", models.IntegerField(blank=True, null=True)),
                ("artist", models.CharField(blank=True, default="", max_length=200)),
                ("flavor_text", models.TextField(blank=True, default="")),
                (
                    "national_pokedex_numbers",
                    models.JSONField(blank=True, default=list),
                ),
                ("legalities", models.JSONField(blank=True, default=dict)),
                (
                    "regulation_mark",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("rules", models.JSONField(blank=True, default=list)),
                (
                    "set",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cards",
                        to="api.set_master",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Card Master Database",
                "ordering": ["set__set_name", "card_name", "card_number"],
            },
        ),
        migrations.AddField(
            model_name="card_listing",
            name="card_master",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="api.card_master",
            ),
        ),
        migrations.AddField(
            model_name="card_listing",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sold_listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="SetTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=200)),
                (
                    "set_master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="api.set_master",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Set Translations",
                "unique_together": {("set_master", "language")},
            },
        ),
        migrations.CreateModel(
            name="CardTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=300)),
                ("image_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "card_master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="api.card_master",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Card Translations",
                "unique_together": {("card_master", "language")},
            },
        ),
        migrations.CreateModel(
            name="CardPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=50)),
                ("variant", models.CharField(max_length=50)),
                ("currency", models.CharField(max_length=3)),
                (
                    "low",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "mid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "market",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "direct_low",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "card_master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="api.card_master",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Card Prices",
                "unique_together": {("card_master", "source", "variant")},
            },
        ),
        migrations.AddIndex(
            model_name="card_master",
            index=models.Index(
                fields=["card_name"], name="api_card_ma_card_na_06d190_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="card_master",
            index=models.Index(
                fields=["supertype"], name="api_card_ma_superty_cab3e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="card_master",
            index=models.Index(
                fields=["card_rarity"], name="api_card_ma_card_ra_798d65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="card_master",
            index=models.Index(fields=["artist"], name="api_card_ma_artist_11adeb_idx"),
        ),
    ]
