# Generated by Django 4.2.7 on 2026-03-29 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=50)),
                ("variant", models.CharField(max_length=50)),
                ("currency", models.CharField(max_length=3)),
                (
                    "low",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "mid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "market",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card_master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="api.card_master",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Card Price History",
                "ordering": ["fetched_at"],
                "indexes": [
                    models.Index(
                        fields=["card_master", "source", "variant", "fetched_at"],
                        name="api_cardpri_card_ma_eb3801_idx",
                    )
                ],
            },
        ),
    ]
