# Generated by Django 4.2.7 on 2026-03-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_cardpricehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="card_master",
            name="language",
            field=models.CharField(db_index=True, default="en", max_length=10),
        ),
        migrations.AddField(
            model_name="set_master",
            name="language",
            field=models.CharField(db_index=True, default="en", max_length=10),
        ),
        migrations.AlterField(
            model_name="card_master",
            name="api_id",
            field=models.CharField(
                max_length=60, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="set_master",
            name="set_code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="set_master",
            unique_together={("set_code", "language")},
        ),
    ]
