# Generated by Django 4.2.7 on 2026-04-03 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_add_language_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('RAW', 'Raw (Ungraded)'), ('PSA', 'PSA Graded'), ('BGS', 'BGS Graded'), ('CGC', 'CGC Graded'), ('TAG', 'TAG Graded'), ('ACE', 'ACE Graded')], help_text='Grading company (PSA, BGS, CGC, etc.)', max_length=4)),
                ('grade', models.DecimalField(decimal_places=1, help_text='Numeric grade, e.g. 9.5 or 10.0', max_digits=4)),
                ('cert_number', models.CharField(help_text='Grading certificate/population report ID.', max_length=50, unique=True)),
                ('graded_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade_detail', to='api.card_listing')),
            ],
            options={
                'verbose_name': 'Card Grade',
                'verbose_name_plural': 'Card Grades',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(max_length=100, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, default='', max_length=100)),
                ('amount_chf', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=10)),
                ('stripe_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='api.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='api_transac_status_0f4e6a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_price_chf', models.DecimalField(decimal_places=2, max_digits=8)),
                ('counter_price_chf', models.DecimalField(blank=True, decimal_places=2, help_text="Seller's counter-offer price, set when status=COUNTERED.", max_digits=8, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('COUNTERED', 'Countered')], default='PENDING', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='api.card_listing')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['listing', 'status'], name='api_offer_listing_56c479_idx'), models.Index(fields=['buyer', 'status'], name='api_offer_buyer_i_bec69c_idx')],
            },
        ),
    ]
