# Generated by Django 4.2.7 on 2026-04-03 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_phase2_offer_transaction_cardgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_listing',
            name='auto_grade',
            field=models.JSONField(blank=True, help_text='ML grading result: {grade, confidence, detectedCard}', null=True),
        ),
        migrations.AddField(
            model_name='card_listing',
            name='grading_status',
            field=models.CharField(choices=[('none', 'None'), ('queued', 'Queued'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='none', max_length=12),
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_key', models.CharField(max_length=500)),
                ('s3_bucket', models.CharField(default='', max_length=200)),
                ('mime_type', models.CharField(default='image/jpeg', max_length=80)),
                ('size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.card_listing')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
