# Generated by Django 5.2.12 on 2026-04-06 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_fraud_dispute"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dispute",
            new_name="api_dispute_status_309981_idx",
            old_name="api_dispute_status_idx",
        ),
        migrations.RenameIndex(
            model_name="dispute",
            new_name="api_dispute_order_i_c78eca_idx",
            old_name="api_dispute_order_idx",
        ),
        migrations.RenameIndex(
            model_name="pricesoldsnapshot",
            new_name="api_priceso_card_id_2d313c_idx",
            old_name="api_pricesoldsnapshot_card_sold_at_idx",
        ),
        migrations.RenameIndex(
            model_name="pricesoldsnapshot",
            new_name="api_priceso_tcg_typ_29ff54_idx",
            old_name="api_pricesoldsnapshot_tcg_type_idx",
        ),
        migrations.RenameIndex(
            model_name="pricesoldsnapshot",
            new_name="api_priceso_conditi_119849_idx",
            old_name="api_pricesoldsnapshot_condition_idx",
        ),
        migrations.RenameIndex(
            model_name="review",
            new_name="api_review_seller__324a38_idx",
            old_name="api_review_seller_created_idx",
        ),
        migrations.RenameIndex(
            model_name="userflag",
            new_name="api_userfla_user_id_06dab3_idx",
            old_name="api_userflag_user_reason_idx",
        ),
        migrations.RenameIndex(
            model_name="userflag",
            new_name="api_userfla_reviewe_f531ed_idx",
            old_name="api_userflag_reviewed_idx",
        ),
        migrations.AlterField(
            model_name="card_listing",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name="card_listing",
            index=models.Index(
                fields=["seller", "is_available"], name="api_card_li_seller__968245_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="card_listing",
            index=models.Index(
                fields=["is_available"], name="api_card_li_is_avai_3eec10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cardprice",
            index=models.Index(
                fields=["card_master"], name="api_cardpri_card_ma_d89886_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["buyer", "status"], name="api_order_buyer_i_35d4b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="api_order_status_dee4b6_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["-created_at"], name="api_order_created_76e476_idx"
            ),
        ),
    ]
